/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protobuf

package org.apache.drill.exec.proto.beans;

public enum SchedulingMessageType implements com.dyuproject.protostuff.EnumLite<SchedulingMessageType>
{
    ADMIT_QUERY_TO_QUEUE(0),
    WAIT_QUERY_FOR_QUEUE(1),
    SERVER_BUSY(2),
    NOT_A_LEADER_FOR_QUEUE(3),
    QUERY_COMPLETE(4),
    SCHEDULE_A_QUERY(5);
    
    public final int number;
    
    private SchedulingMessageType (int number)
    {
        this.number = number;
    }
    
    public int getNumber()
    {
        return number;
    }
    
    public static SchedulingMessageType valueOf(int number)
    {
        switch(number) 
        {
            case 0: return ADMIT_QUERY_TO_QUEUE;
            case 1: return WAIT_QUERY_FOR_QUEUE;
            case 2: return SERVER_BUSY;
            case 3: return NOT_A_LEADER_FOR_QUEUE;
            case 4: return QUERY_COMPLETE;
            case 5: return SCHEDULE_A_QUERY;
            default: return null;
        }
    }
}
